version: "3.9"

services:
  db:
    image: postgres:16
    container_name: aurora_postgres
    restart: always
    environment:
      POSTGRES_DB: aurora-database
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: 5e5i_aurora
    ports:
      - "5432:5432"
    volumes:
      - aurora_data:/var/lib/postgresql/data
    networks:
      - aurora_network

volumes:
  aurora_data:

networks:
  aurora_network:
    driver: bridge
